### ISSUE TITLE
SpatialOS Launcher only accept client workers named with UnityClient/UnrealClient/LauncherClient

### ISSUE THREAD

**Issue by No3371** [spatialos/gdk-for-unity#1410]
I encountered an issue that whenever I try to launch my game from SpatialOS console, the launcher always pops out a modal says "error fetching client details".

My client worker was named "PlayerClient", after messing with all the config files for half a day, I looked into the launcher log file and figured out it only looked for "UnityClient", "UnrealClient", "LauncherClient".

I don't know where is this kept in the documentation, but I consider the behavior is very inconsistent with server workers, it just does not make sense that we can name server workers whatever we want, while custom named client workers just fail without any valid description.

**Comment by jamiebrynes7** [comment]
Hey @No3371, yeah this is the current behaviour - I'll pass this feedback onto the relevant team!

In the meantime, there's a little bit more information about the [launcher configuration](https://documentation.improbable.io/spatialos-tools/docs/launcher-client-configuration-file#section-3-add-to-your-client-zip) in the documentation.

Is there any particular reason you wanted to change your client name?

**Comment by No3371** [comment]
So it's the **Tools** documentation! I've never looked into there... actually I don't think anyone'd expect this because the [launch configuration file documentation in Spatail Overview](https://documentation.improbable.io/spatialos-overview/docs/spl-launch-configuration-file) mentions this. (neither the flexible one)

It's just no one told me I can't, and **what if I made 2 clients to access 1 game, both with Unity** 🤔 ?

**Comment by No3371** [comment]
> It's just no one told me I can't, and **what if I made 2 clients to access 1 game, both with Unity** 🤔 ?
It suddenly comes to my mind that this is impossible? Can we start clients without SpatialOS launcher?

**Comment by jamiebrynes7** [comment]
> It suddenly comes to my mind that this is impossible? Can we start clients without SpatialOS launcher?

You can definitely start clients without the SpatialOS launcher. The launcher pulls the client build, unzips it, and starts it with a set of command line arguments (crucially a set of login credentials for connecting to the specified cloud deployment).

In development, you can use the [development authentication service](https://documentation.improbable.io/sdks-and-data/docs/authentication-during-game-development) to connect to cloud deployments, but for production you would need to [roll your own authentication service](https://documentation.improbable.io/sdks-and-data/docs/create-an-authentication-server-overview) in order to login users and grant them login tokens.

**Comment by No3371** [comment]
Thanks for the quick answer, that'd be a really important factor for my office to adopt SpatialOS in the future 😄
